### ISSUE TITLE
Submit Food Items

### ISSUE THREAD

**Issue by dbradley771** [MWHSComputerScience-ORG/StoreSim-APCS2016#13]
Please start submitting the food items you created to our repository.

We would like your food items to look like this and to be placed in the ```interfaces.food``` package:
```java
package interfaces.food;

public class WhippedCream extends Food {
	public WhippedCream() {
		setName("Whipped Cream");
		setCost(0.40);
		setStoreCost(1.00);
		setQuantity(20);
		setExpiration(7);
		setDesirability(1);
	}
}
```
This might break your code for a bit but it should work again if you update your repo on our after we accept your request.

Thanks.

**Comment by dbradley771** [comment]
@MWHSComputerScience-ORG/apcs2016-class do this

**Comment by ckauth97** [comment]
Was that Corbin's?

**Comment by dbradley771** [comment]
No, that was the thing that said to submit their food.

**Comment by ckauth97** [comment]
Oh gotcha I just saw that
